### ISSUE TITLE
throw exception

### ISSUE THREAD

**Issue by github-wujianwen** [BingAds/BingAds-dotNet-SDK#104]
a new project,use nuget to get Microsoft.BingAds.SDK,and debug run,throw exception,,
System.IO.FileLoadException:Could not load file or assembly 'Microsoft.BingAds, Version=13.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.....strong name validation failed

make it x64,it is useless.

**Comment by qitia** [comment]
this sounds like your system setting issue. not sure whether this helps: https://docs.microsoft.com/en-us/archive/blogs/keithmg/strong-name-validation-failed-exception-from-hresult-0x8013141a
