### ISSUE TITLE
Tenant-specific token refresh fails with unexpected request to common endpoint

### ISSUE THREAD

**Issue by victorfrye** [BingAds/BingAds-dotNet-SDK#142]
**Describe the bug**
When trying to request an access token for `msads.manage` scope and a tenant other than `common``, the request is using the common endpoint and may fail if the application is registered in a single tenant.

**To Reproduce**

1. Replace the values in the following code snippet with actuals.

```csharp
using Microsoft.BingAds;

var grant = new OAuthWebAuthCodeGrant(
    clientId: "YOUR_CLIENT_ID",
    clientSecret: "YOUR_CLIENT_SECRET",
    redirectionUri: new("https://example.com/"),
    refreshToken: "YOUR_REFRESH_TOKEN",
    environment: ApiEnvironment.Production,
    oAuthScope: OAuthScope.MSADS_MANAGE,
    tenant: "example.onmicrosoft.com");

await grant.RequestAccessAndRefreshTokensAsync("YOUR_REFRESH_TOKEN");
```

2. Request fails on call to `RequestAccessAndRefreshTokensAsync` with the following example error message:

```
Microsoft.BingAds.OAuthTokenRequestException: Couldn't request OAuth AccessTokens. Please check the Details property for more information. Details: invalid_request - AADSTS50194: Application '{example-guid}'(Example App) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

**Additional context**
- The application scenario I'm working with is not-user facing and thus I already have a refresh token.
- Confirmed to work with the tenant-specific endpoint via Postman.
- Fails in other method calls that refresh the access token under-the-hood and is blocking to applications that are limited to a single tenant.
- I can provide some actual values to demonstrate the issue, but they are obviously sensitive given the nature of identity authorization and authentication.
- Confirmed issue on v13.0.21.1, v13.0.21.0, and v13.0.20.1

**Comment by victorfrye** [comment]
I opened a draft PR because this seems like a simple fix with a potentially newer EndpointType of ` OAuthEndpointType.ProductionMSIdentityV2_MSScope` wasn't included in the conditionals to replace common tenant with the actual.

i.e.: https://github.com/BingAds/BingAds-dotNet-SDK/blob/main/BingAdsApiSDK/Internal/OAuth/UriOAuthService.cs#L124-L127

**Comment by xinyuwen2** [comment]
I just merged the PR. Thank you for fixing it!
