### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by rv-bbassham** [BingAds/BingAds-dotNet-SDK#30]
Having the ability to use the BingAds API directly from .Net Core would be a great feature.

**Comment by michael-j-chinn** [comment]
I am very interested in seeing this SDK work in .net core. Is this coming anytime soon?

**Comment by litan1106** [comment]
+1 for .Net Core support

**Comment by eric-urban** [comment]
@rv-bbassham @michael-j-chinn @litan1106 we are investigating this now. Thanks for the suggestion!

**Comment by qitia** [comment]
Currently we are working on SDK targeting NetStandard2.0(which support .Net Core2.0). Is that what you want? @rv-bbassham @michael-j-chinn @litan1106

**Comment by eric-urban** [comment]
@rv-bbassham @michael-j-chinn @litan1106 support for .NET Core (via .NET Standard 2.0) is added with [v11.12.1](https://github.com/BingAds/BingAds-dotNet-SDK/releases/tag/v11.12.1). Thanks again for the suggestion.
