### ISSUE TITLE
bulk FileUploadParameters - Internal property messing up the file uploading

### ISSUE THREAD

**Issue by stark526** [BingAds/BingAds-dotNet-SDK#36]
Hi :)
I tried to use the "BulkServiceManager" to upload a bulk of entities using the method "UploadFileAsync(FileUploadParameters parameters)", but every time i got the exception "BulkOperationCouldNotBeCompletedException". 
after some digging, i found out that the field "RenameUploadFileToMatchRequestId" should be true in order for the request to succeed, but i can't control it outside of the sdk, because it is an internal property (expect of course, using reflection). So my question is: Why does this property needs to be internal?

The SDK version I'm using is 11.5.1.0

(by the way, the issue is in both V10 and V11)

**Comment by eric-urban** [comment]
Hello. I'm not able to repro the issue with UploadFileAsync. Do you have an example?

**Comment by stark526** [comment]
This code below is an example to a code that will throw a BulkOperationCouldNotBeCompletedException exception. If you uncomment the comment lines (which use reflection to change the RenameUploadFileToMatchRequestId field) you'll see that you don't get this exception anymore and the file is uploaded properly.

long accountId = YOUR_ACCOUNT_ID;
string userName = YOUR_USER_NAME;
string password = YOUR_PASSWORD;
long customerId = YOUR_CUSTOMER_ID;
string devTOken = YOUR_DEVELOPER_TOKEN;

var serviceManager = new BulkServiceManager (
    new AuthorizationData
    {
        AccountId = accountId,
        Authentication = new PasswordAuthentication(userName, password),
        CustomerId = customerId,
        DeveloperToken = devTOken
    });
var path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
var bulkWriter = new BulkFileWriter(path);
bulkWriter.WriteEntity(new BulkCampaign
{
    AccountId = accountId,
    Campaign = new Campaign()
});
bulkWriter.Dispose();
var fileUploadParameters = new FileUploadParameters
{
    CompressUploadFile = true,
    OverwriteResultFile = true,
    ResponseMode = ResponseMode.ErrorsAndResults,
    ResultFileDirectory = Path.GetTempPath(),
    ResultFileName = Guid.NewGuid() + ".txt",
   UploadFilePath = path
};

//var type = typeof(FileUploadParameters);
//var prop = type.GetProperty("RenameUploadFileToMatchRequestId", BindingFlags.NonPublic | BindingFlags.Instance);
//prop.SetValue(fileUploadParameters, true);

var result = await serviceManager.UploadFileAsync(fileUploadParameters);

**Comment by eric-urban** [comment]
In this case the upload is failing because you are missing the .csv or .tsv extension. Per the [technical guide](https://msdn.microsoft.com/en-us/library/bing-ads-bulk-download-and-upload-guide.aspx#bulkupload), Bulk upload supports .csv and .tsv only. **_Note_**: Currently the guide only mentions that the file must be "formatted" as Csv or Tsv, and we will update it to clarify that the extension must also match.

The following change (append .csv) works:
`var path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString()) + ".csv";`

I hope this helps!

**Comment by stark526** [comment]
Thanks, that did solve the problem.
I have 2 more questions about that issue:

1. Why there is a RenameUploadFileToMatchRequestId field? it looks like this field is not in use in any case (it's always false and couldn't be change outside of the library).

2. Shouldn't the BulkFileWriter make sure that your path has the proper extension? If you can choose the type of the file on the BulkFileWriter, it make sense that it will also make sure that the file that he writes to will also have the same extension (And will also spare the user from that issue) .

Thanks for the help :)

**Comment by eric-urban** [comment]
@stark526 The purpose of the RenameUploadFileToMatchRequestId parameter is to improve troubleshooting when calling UploadEntitiesAsync (basically we want the temporary upload file generated by the SDK to have the same name as the corresponding upload request id). It's used in CreateFileUploadParameters, which takes entities to upload as an input, writes them to a temporary file and sets RenameUploadFileToMatchRequestId to true. After calling GetBulkUploadUrlAsync we have the upload RequestId, so we can use this value to rename the temporary file.
