### ISSUE TITLE
Debug build is published build

### ISSUE THREAD

**Issue by amh9002** [BingAds/BingAds-dotNet-SDK#49]
Currently, the debug build is being published on nuget. Is this by design? If not, can the Release version be published instead? Causing issues with "Just My Code" debugging.

**Comment by qitia** [comment]
Which version are you using?

**Comment by amh9002** [comment]
Sorry, I am using the latest version on nuget (11.5.4). I did verify 11.5.3 was the same.

**Comment by qitia** [comment]
![sdkinfo](https://user-images.githubusercontent.com/29188289/29445808-4d27d6f4-841b-11e7-9bb5-5b11b3749c41.jpg)
I just checked the dll info. Seems to me it is a release version... How do you think it is a debug version?

**Comment by amh9002** [comment]
I was getting source code not found errors related to the SDK when I was trying to debug my project, so I assumed that VS was seeing the dll as my code instead of a third party library. Until your last post, I had never seen the assembly info tool before so I pulled down the 11.5.4 and 11.5.3 releases to check the active build profiles in the solution. They were set to debug so I assumed the releases were built with the debug profile (probably shouldn't have made that assumption :smile: ). I was able to find the tool you used for the screenshot in your last comment and verified the dll is the release version. 

Here is a screenshot of what I get when I try to debug. Stepping over works, but I use F11 to step into my own code expecting SDK calls to automatically be stepped over. 

![sdkissue](https://user-images.githubusercontent.com/8409397/29447005-2bad21f2-83b5-11e7-9851-789ddb7e1413.png)

Pulling down the source and building the library with the release profile (with the debug info output set to none) I get the desired result. However, I would like to avoid doing this and use Nuget instead. Maybe I have some settings incorrect, but i've used several libraries pulled from Nuget under my current settings. 

If you have any ideas, I would appreciate the help. If not, the issue can be closed as it's been validated that the published dll is in fact the release version. Either way, I  appreciate you taking the time to look into this.

**Comment by qitia** [comment]
I am not sure about how this could happen. The SDK DLL is signed to avoid abuse, could this be the cause?

**Comment by amh9002** [comment]
I removed and reinstalled the nuget package and noticed that the pdb is included. I renamed the file to Microsoft.BingAds.pdb.bak and now debugging works as expected. I guess the presence of the pdb incorrectly told the debugger that the SDK was my code and it should look for the source. Should the pdb be included in the nuget package? Again, thanks for the help.
