### ISSUE TITLE
Missing columns in KeywordPerformanceReport

### ISSUE THREAD

**Issue by betabandido** [BingAds/BingAds-dotNet-SDK#54]
We are trying to download `Mainline1Bid`, `MainlineBid` and `SidebarBid` columns for the `KeywordPerformanceReport` using the SDK. But, they are not present in the enum
`KeywordPerformanceReportColumn`.

Will they be included?

Thanks!

**Comment by eric-urban** [comment]
@betabandido these columns were added with release 11.5.7. Thanks for your patience!
