### ISSUE TITLE
No Example for use of "IN" Predicate

### ISSUE THREAD

**Issue by tomwarner13** [BingAds/BingAds-dotNet-SDK#64]
I have a list of Account Numbers, and I would like to use the SearchAccounts API to return all associated accounts. It appears the obvious way to do this would be by using a Predicate for the search with an IN operator: for example:

`          new Predicate
          {
            Field = "AccountNumber",
            Operator = PredicateOperator.In,
            Value = "Number1,Number2,Number3"
          }`

This code does not work--it returns an error which tells me the predicate value is invalid. However, I have no idea how to correctly format this value. There are literally no examples I could find for its use--either here, or in the official Bing Ads docs, or anywhere else online.

Seeing as this is presumably a feature you'd like people to use, would you mind actually explaining how it works somewhere? If I figure it out on my own I will happily submit a PR.

**Comment by tomwarner13** [comment]
Turns out it works with ';' as the separator. PR incoming.

**Comment by eric-urban** [comment]
@tomwarner13 officially the values should be comma separated per [docs here](https://docs.microsoft.com/en-us/bingads/customer-management-service/predicateoperator?view=bingads-12#in). I tested and found that either semicolon or comma work for this scenario, although I recommend using the documented separator. You mentioned comma did not work for you, so in that case please feel free to [contact support](http://go.microsoft.com/fwlink/?LinkId=269631) with details e.g., trace with request, response, and timestamp.

**Comment by tomwarner13** [comment]
Well in that case who even needs an example anyway?
