### ISSUE TITLE
Add multi targeting platforms support for net461

### ISSUE THREAD

**Issue by myatyga** [BingAds/BingAds-dotNet-SDK#66]
Hi
Could you please add support target framework version net461?
Because have problem with netstandard2.0 on visual studio 2015 pro.

**Comment by qitia** [comment]
per doc [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), netframework 4.6.1 can be supported by netstandard2.0. the constraint is that you need to upgrade to VS2017, or upgrade tooling, did you try that? @myatyga

**Comment by myatyga** [comment]
Thanks, I will try to resolve conflicts.

**Comment by myatyga** [comment]
After installing Bing SDK have problems like this:

>CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Program Files (x86)\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XmlSerializer.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Xml.XmlSerializer.dll'. Remove one of the duplicate references.

Have a idea to resolve problem?

**Comment by qitia** [comment]
no idea on this, could [this](https://github.com/dotnet/sdk/issues/1539) help?

**Comment by qitia** [comment]
@myatyga I close this issue and let me know if you have further question.
