### ISSUE TITLE
BingAds 11.12.7 incompatible with .net framework 4.5.2

### ISSUE THREAD

**Issue by moashor** [BingAds/BingAds-dotNet-SDK#70]
Hallo, While upgrading Microsoft.BingAds.SDK to versios 11.12.7, I got an error message that .net framework 4.5.2 is not valid. Must I update the .net framework to 4.6 to be able to upgrade Microsoft.BingAds.SDK to versios 11.12.7 ?

**Comment by qitia** [comment]
yes, netframework 4.6.1 and later is required since Bingads SDK version 11.12.1
