### ISSUE TITLE
Nuget package BingAds v11.12.7 causes error on TFS build

### ISSUE THREAD

**Issue by moashor** [BingAds/BingAds-dotNet-SDK#71]
Nuget package BingAds v11.12.7 causes error on TFS build the error is "you must add a referenece netstandard.dll"

I am not getting this error on my local machine but i get it on my TFS build.
if i downgrad to v11.5.8 the TFS build work again successfully.

Could you please help ?

**Comment by qitia** [comment]
use VS2017 and msbuild 15.8.0+ resolve the issue.
