### ISSUE TITLE
Processor architecture mismatch v12.13.1

### ISSUE THREAD

**Issue by juliuscaesarnl** [BingAds/BingAds-dotNet-SDK#76]
Hi,

I recently updated the NuGet package for my Windows Forms App to version 12.13.1.
Now I'm seeing a build warning about a mismatch between the processor architecture of my project and the reference. My project is set to 'MSIL', while the reference is set to 'AMD64'.
Was this change intended?

Thanks in advance.

**Comment by mayerwin** [comment]
Same issue here.

**Comment by stewart-r** [comment]
Affecting us too

**Comment by eric-urban** [comment]
@juliuscaesarnl @mayerwin @stewart-r we updated the target platform from x64 to AnyCPU in version [12.13.4](https://github.com/BingAds/BingAds-dotNet-SDK/releases/tag/v12.13.4). Does this help?
