### ISSUE TITLE
IReportRecord can't parse doubles in some cultures

### ISSUE THREAD

**Issue by gvidasja** [BingAds/BingAds-dotNet-SDK#77]
`IReportRecord.GetDoubleValue` method throws an exception "Input string was not in a correct format.", if the number formats on the client machine use commas instead of dots for decimal fractions.

For example, my machine uses comma-delimited decimals and if I download a report like this:
```
"AdGroupId","Conversions"
"123123123","2.38"
"456456456","2.48"
```
parsing the `Conversions` column will fail unless I fix the report manually like this
```
"AdGroupId","Conversions"
"123123123","2,38"
"456456456","2,48"
```

There is a workaround to parse the double manually with a specified `CultureInfo`:
```
double.Parse(reportRecord.GetStringValue("Conversions"), new CultureInfo("en-US"));
```
However, this is obviously not ideal.

Maybe the library could ensure that it uses the same formats for parsing as for report generation?

**Comment by qitia** [comment]
Thanks @gvidasja , I will look into this and come back.

**Comment by qitia** [comment]
hi @gvidasja [Version 12.13.3](https://github.com/BingAds/BingAds-dotNet-SDK/releases/tag/v12.13.3) was released June 24, in which we handle this inside the lib itself. You can use GetDoubleValue directly now.
