### ISSUE TITLE
Error in report Download using Bing Ads API v12

### ISSUE THREAD

**Issue by Swapygit** [BingAds/BingAds-dotNet-SDK#78]
Hi Team,

I am trying to download the Bing Ads report using v12 BingAds API. The API is working fine. but I am getting the following exception for some of the Bing Account Ids.

"Submit download operation failed." and Inner Exception as  "Invalid client data. Check the SOAP fault details for more information"

can you please tell me with this issue. I checked on BingAds dashboard and the data is present for those Bing AccountIds, but are not downloaded using BingAdsAPI.

**Comment by qitia** [comment]
Hi @Swapygit , "Invalid client data. Check the SOAP fault details for more information" is a very common error, we can not tell what was happened by this error itself. Could you please provide some more info like "TrackingId", "RequestId" and datetime when you made the download?

**Comment by eric-urban** [comment]
@Swapygit please feel free to reopen with more details. Thanks!
