### ISSUE TITLE
Is the password Authentication method still supported? I see the code for it. Just wondering

### ISSUE THREAD

**Issue by zerobounce** [BingAds/BingAds-dotNet-SDK#87]
Is the password Authentication method still supported? I see the code for it. Just wondering

**Comment by qitia** [comment]
yes existing users with legacy Bing Ads credentials may continue to specify the UserName and Password header elements. But it is suggest to use OAuth authentication. In future versions of the API, Bing Ads will transition exclusively to Microsoft Account authentication.
