### ISSUE TITLE
what Authentication object to use when you want to use existing OAuthTokens from local saved file.

### ISSUE THREAD

**Issue by litan1106** [BingAds/BingAds-dotNet-SDK#88]
For example:
I want to call the reporting service with the saved the OAuthToken from local file.

```
 var authGrant = (OAuthDesktopMobileAuthCodeGrant) authData.Authentication;

authGrant.OAuthTokens = new OAuthTokens(oldToken.AccessToken, 3600, oldToken.RefreshToken);
```
However, I couldn't set the OAuthTokens from saved OAuthToken because the internal access.

![image](https://user-images.githubusercontent.com/1310539/85776472-9c03b780-b6d5-11ea-951d-a67f28b8e5e8.png)

* I saved the previous request OAuthTokens to a local file. (serialized)

Authentication objects:
```
   T:Microsoft.BingAds.OAuthDesktopMobileAuthCodeGrant

   T:Microsoft.BingAds.OAuthDesktopMobileImplicitGrant

   T:Microsoft.BingAds.OAuthWebAuthCodeGrant

   T:Microsoft.BingAds.PasswordAuthentication
```

**Comment by qitia** [comment]
hi @litan1106, in fact you should not save the total OAuth info in local file, as the access token is expected to be expired in around 1 hour. you could save the refresh token somewhere and use it with RequestAccessAndRefreshTokensAsync, Both OAuthDesktopMobileAuthCodeGrant and OAuthWebAuthCodeGrant support this method.

You should also know that the refresh token is also expired in some time/cases, so make sure you update your saved refresh token when you get a new one. see [here](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth?view=bingads-13) for more detail.

**Comment by litan1106** [comment]
@qitia I was trying reuse the access token across multiple report requests in the C# Bing Ads SDK. @eric-urban [showed us a way to do that in Bing Ads Java SDK](https://social.msdn.microsoft.com/Forums/en-US/97334a92-f520-47ae-b56c-acb6adf20aea/setting-access-token-myself?forum=BingAds). However, I couldn't find a way to do in the C# world.

**Comment by qitia** [comment]
I think java and dotnet share the exact same concept in this part :). Please show us which is not feasible to c# in Eric's sample. @eric-urban  FYI.

**Comment by litan1106** [comment]
In the C# Bing Ads SDK, we have to implement SetAuthenticationFieldsOnApiRequestObject when we extends Authentication.
I wasn't sure what to do there.

```using System;
using System.Net.Http.Headers;
using Microsoft.BingAds;

namespace ClientDashboard.Infrastructure.BingAds
{
    public class BACustomOAuth : Authentication
    {
        private string AccessToken { get; set; }

        public BACustomOAuth(string accessToken)
        {
            AccessToken = accessToken;
        }
        
        protected override void SetAuthenticationFieldsOnApiRequestObject(object apiRequest)
        {
            // What to do here?
            throw new NotImplementedException();
        }

        protected override void AddAuthenticationHeaders(HttpRequestHeaders requestHeaders)
        {
            requestHeaders.Add("AuthenticationToken", AccessToken);
        }
    }
}```

Reference to [my Bing Ads forum post.](https://social.msdn.microsoft.com/Forums/en-US/51408a92-8ab9-4cb5-872b-084137994fb5/setting-access-token-myself-with-bingads-net-sdk?forum=BingAds)

**Comment by eric-urban** [comment]
@litan1106 I did not yet try this via .NET. Regarding your question about SetAuthenticationFieldsOnApiRequestObject, have you tried setting apiRequest.AuthenticationToken = YOUR_ACCESS_TOKEN i.e., similar as via [OAuthAuthorization](https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/BingAdsApiSDK/Internal/OAuthAuthorization.cs#L153)?

**Comment by litan1106** [comment]
> @litan1106 I did not yet try this via .NET. Regarding your question about SetAuthenticationFieldsOnApiRequestObject, have you tried setting apiRequest.AuthenticationToken = YOUR_ACCESS_TOKEN i.e., similar as via [OAuthAuthorization](https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/BingAdsApiSDK/Internal/OAuthAuthorization.cs#L153)?

I tried it the BACustomOAuth but I ran into the exception. (The SetAuthenticationFieldsOnApiRequestObject was called by the https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/BingAdsApiSDK/ServiceClient.cs#L194)
```
System.AggregateException: One or more errors occurred. (Submit download operation failed.)
 ---> Microsoft.BingAds.V13.Reporting.CouldNotSubmitReportingDownloadException: Submit download operation failed.
 ---> System.NotImplementedException: The method or operation is not implemented.
   at ClientDashboard.Infrastructure.BingAds.BACustomOAuth.SetAuthenticationFieldsOnApiRequestObject(Object apiRequest) in C:\Codes\ClientDashboard\src\Infrastructure\Bi
ngAds\BACustomOAuth.cs:line 19
```

**Comment by eric-urban** [comment]
@litan1106 this works for me (for testing, I added a class [here](https://github.com/BingAds/BingAds-dotNet-SDK/tree/master/examples/BingAdsExamples/BingAdsExamplesLibrary/v13)):

```csharp
using System;
using System.Net.Http.Headers;
using Microsoft.BingAds;

namespace BingAdsExamplesLibrary.v13
{
    public class BACustomOAuth : Authentication
    {
        private string AccessToken { get; set; }

        public BACustomOAuth(string accessToken)
        {
            AccessToken = accessToken;
        }

        protected override void SetAuthenticationFieldsOnApiRequestObject(dynamic apiRequest)
        {
            if (AccessToken == null)
            {
                throw new InvalidOperationException("OAuth access token is missing or invalid.");
            }

            apiRequest.AuthenticationToken = AccessToken;
        }

        protected override void AddAuthenticationHeaders(HttpRequestHeaders requestHeaders)
        {
            requestHeaders.Add("AuthenticationToken", AccessToken);
        }
    }
}
```

Does this help?

**Comment by litan1106** [comment]
It worked. Thanks for the help. @eric-urban @qitia
