### ISSUE TITLE
Reaching OfflineConversion Upload Limit

### ISSUE THREAD

**Issue by cdjvweb** [BingAds/BingAds-dotNet-SDK#92]
Dear BingAds Team, 

Our Current production code is using : 
- bingads sdk version 13.0.2.1
- .net Framework 4.7.2
- Azure Function 1.0.26 

My issue :
With the blackfriday, We are currently reaching the OfflineConversionUploadLimit,

My Questions :

- Is it possible to increase this limit ?
- If not how can I work around  this limit ?
- Should I batch OfflineConversion per 1000 between differents ApplyOfflineConversionsRequest ?

Thanks For your help.

**Comment by qitia** [comment]
@cdjvweb , true you need to split the payload into batch, there is no way to work around from my understanding.
