### ISSUE TITLE
Still too many Http connections (release 13.0.9)

### ISSUE THREAD

**Issue by jesuissur** [BingAds/BingAds-dotNet-SDK#95]
Hello there!

As stated in a [previous issue](https://github.com/BingAds/BingAds-dotNet-SDK/issues/94#issuecomment-829293865) we still have high http connections consumption in our app.

In [our fork](https://github.com/DashThis/BingAds-dotNet-SDK) we added a way to customize/replace the Http clients creation.  Our fork includes the latest WCF nuget packages (4.8.1) to have a similar change from their side: https://github.com/dotnet/wcf/pull/2534

If you need an official pull request or anything else, just let us know.

Thanks,
Phil

**Comment by qitia** [comment]
Thanks @jesuissur.  in your fork, I see you create a HttpClientFactory class, and you initiate HttpClient instance from here. May I know how do you define GetHttpClientWithEfficientSocketsUsage() from caller side?

**Comment by jesuissur** [comment]
Sure @qitia.  We instantiate it through the IServiceProvider (Dependency injection).

1. We configure an http client through the `IServiceCollection.AddHttClient<>`.  A bit like that: `services.AddHttpClient<OurBingHttpClient>().ConfigurePrimaryHttpMessageHandler(x => new SocketsHttpHandler { MaxConnectionsPerServer = 5 }).SetHandlerLifetime(5.Minutes())`
2. Then we go through the Dependency injection to resolve the handler we give to the Bing SDK.  `serviceProvider.GetService<IHttpMessageHandlerFactory>().CreateHandler("OurBingHttpClient")`
3. So we end up with a call in our app startup like this one
```
HttpClientCustomFactory.ReplaceHttpClientFactory(() => serviceProvider.GetService<OurBingHttpClient>().HttpClient,
                                                             () => serviceProvider.GetService<IHttpMessageHandlerFactory>()
                                                                             .CreateHandler("OurBingHttpClient");
```

Hope it helps

Thanks,
Phil

**Comment by qitia** [comment]
Thanks @jesuissur for providing the approach, and try to include that in next release.

**Comment by qitia** [comment]
please try version 13.0.11 @jesuissur
